server:
  port: 8082

spring:
  application:
    name: center-service
  datasource:
    url: jdbc:mysql://localhost:3306/center_db
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    discovery:
      enabled: true
    config: 
      enabled: false
  cache:
    type: redis 
  
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true      
    fetch-registry: true           
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: center-service      
    prefer-ip-address: true   
  