server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  cache:
    type: redis 
  
  config:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: user-service         
    prefer-ip-address: true 