server:
  port: 8089
spring:
  application:
    name: communication-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/communication_db?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  config:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: communication-service       
    prefer-ip-address: true 