server:
  port: 8081
spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:http://localhost:8888"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: booking-service            
    prefer-ip-address: true 