server:
  port: 8086
spring:
  application:
    name: vehicle-part-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_part_db?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  config:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: vehicle-part-service        
    prefer-ip-address: true 