server:
  port: 8067

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthFilter    
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuthFilter  
        - id: center-service
          uri: lb://center-service
          predicates:
            - Path=/api/stations/**
          filters:
            - JwtAuthFilter
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - JwtAuthFilter  
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/service-orders/**
          filters:
            - JwtAuthFilter  
        - id: vehicle-part-service
          uri: lb://vehicle-part-service
          predicates:
            - Path=/api/vehicles/**, /api/parts/**
          filters:
            - JwtAuthFilter

        
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtAuthFilter                    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
